### ISSUE TITLE
Feature: User can search for cards.

### ISSUE THREAD

**Issue by krog-kristian** [krog-kristian/tcg-tracker#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for cards.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will come to home page and be able to search for Pokemon cards by name.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Mobile-Home-Screen](https://user-images.githubusercontent.com/118767169/221718959-e7859b36-d54b-4740-a05f-01f745cb4391.png)
![Mobile Search](https://user-images.githubusercontent.com/118767169/221718979-0fe6a13d-5839-4e80-864f-87303fc587d2.png)
![Figma-mobile-hamburger](https://user-images.githubusercontent.com/118767169/221718988-c417c535-f15e-4e37-8bcb-21ea6ebe21e0.png)
![Desktop-home-page](https://user-images.githubusercontent.com/118767169/221718999-a6492274-de97-47c6-8e59-cb2077c054bb.png)
![Desktop-search](https://user-images.githubusercontent.com/118767169/221719006-a5988030-9036-44b7-9b04-4a6383c458ca.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Build HTML for Home Page.
- [x] Style Home Page to match Figma.
- [x] Build a view swap function.
    - [x] Build a data object with 1 property, view.
    - [x] Check current view.
    - [x] Unhide new view and hide old view and set data view to new view.
    - [x] Build hamburger menu opened.
    - [x] Also attach it to the hamburger menu.
- [x] Add event listener to search bar.
   - [x] Retrieve name entered into search bar.
   - [x] Have placeholder be default value.
   - [x] Checks current view and toggles if on Home Page.
- [x] Query the API for name of searched Pokemon.
- [x] Style returned cards to match Figma Layout using dummy data.
- [x] Build a render function based on the image URL for a card object passed as the parameter.
    - [x] Uses image URL from the object to create an image.
    - [x] Attaches array index to the card wrapper div.
    - [x] Returns the DOM tree.  
- [x] Build a function to pass search results through the render.
    - [x] Pass the objects from data array though the render function.
    - [x] Append them to the search result container as a new row. 
- [x] Add link for home page on desktop in navbar.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
