### ISSUE TITLE
Feature: User can pop a card up to view larger image. 

### ISSUE THREAD

**Issue by krog-kristian** [krog-kristian/tcg-tracker#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can pop a card up to view a larger image.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to click an image and have it pop up and be enlarged and when clicked again will go back.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue-6-mobile](https://user-images.githubusercontent.com/118767169/223180087-15f8c4b6-074c-4f48-857a-4334524cc196.png)
![issue-6-desktop](https://user-images.githubusercontent.com/118767169/223180161-e8394fe2-33b5-4e69-a4e6-74074b49ea07.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Try using visibility change event listener with before unload to save, data for mobile devices.
- [x] Create a new modal in HTML.
- [x] Use a template image to style it for both mobile and desktop, using the large image from the API.
- [x] Listen to the card images on all pages
- [x] When clicked have a function called that will pop the modal up and use the card ID from the card wrapper.
- [x] Search through the collection for the ID and grab the large image URL and assign it to the source of the modal.
- [x] When the image is clicked again clear the source and pop down the modal.
- [x] Use the card name for the alt attribute of the pop up image.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
