### ISSUE TITLE
Bug: Card count, counts too often.

### ISSUE THREAD

**Issue by krog-kristian** [krog-kristian/tcg-tracker#13]
#### Desired Behavior

> ##### The app should ...

On sets page only listen to the add card button.
#### Actual Behavior

> ##### The app does this instead ...

The app listens to the checkmark icon as well.
#### Steps to Reproduce

> ##### To trigger the bug, you must ...

Click on the green checkmark.
## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Check event listeners for set page.
- [x] Check conditional statement for count cards function.
- [x] Ensure only add button triggers count cards function.
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
