### ISSUE TITLE
Feature: User can save a card to a collection.

### ISSUE THREAD

**Issue by krog-kristian** [krog-kristian/tcg-tracker#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to add cards to their collection.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user searches cards their will be a collect button which will save the card to a "Your Collection" page. They will then be able to view all cards they saved.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Figma-mobile-hamburger](https://user-images.githubusercontent.com/118767169/222217395-d063f0f5-1b9a-499d-be5f-9f8500678a26.png)
![issue-2 mobile](https://user-images.githubusercontent.com/118767169/222217412-47fa9c07-86f4-4a31-9153-e234992e164d.png)

![Desktop-search](https://user-images.githubusercontent.com/118767169/222217443-312bc383-69ae-4fa6-bfab-2d5b84e3b1b3.png)
![issue-2-desktop](https://user-images.githubusercontent.com/118767169/222217457-4a50a3ba-ca4e-4c89-b9d0-f720236f4ef0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a new variable to temporarily save the retrieved search object.
- [x] Add properties to the data object to save relevant information from the API' object.
- [x] Set up a new local storage, for TCG Tracker.
- [x] Listen to document load and set data-view to home.
- [x] Update render function to include a plus button for mobile and a collect button for desktop.
   - [x] Add card id to card wrapper and remove array location. 
   - [x] Use CSS to display plus button or collect for appropriate size.
- [x] Listen to results page for clicks on buttons and retrieve the card id.
- [x] Take object from the temporary save of the search that matches card wrapper ID and update the data object.
   - [x] Update render to check if collected cards match search results and render check mark instead if in data.collection. 
   - [x] Update collect button event listener
   - [x] Save, ID, name, supertype, hp, types, images, set (id, name, series),
- [x] Build HTML and style CSS for collection view.
- [x] Add a link to the nav of the desktop and the hamburger menu for collection.
   - [x] Using data-view and data-view-change for collection
- [x] When collection is selected check to see if all cards are rendered or not.
- [x] On document load if data has cards saved set page to collection and render collection.
- [x] Make sure search bars clear data.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
