### ISSUE TITLE
Feature: User can sort their collection.

### ISSUE THREAD

**Issue by krog-kristian** [krog-kristian/tcg-tracker#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sort and filter their collection.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to filter collection by Pokemon type(water, fire etc), by card supertype (pokemon, trainer, energy etc), and sort by HP ascending or descending. User will also be able to search for a card in their collection.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue-2-desktop](https://user-images.githubusercontent.com/118767169/222281936-8033eef0-2e61-4e91-a446-224a80b30c7d.png)
![figma-issue-3-mobile](https://user-images.githubusercontent.com/118767169/222282114-8a98efe0-05db-45f8-b3e2-82aafe10747a.png)
![figma-issue-dropdown](https://user-images.githubusercontent.com/118767169/222282221-840f905f-f51f-4cb6-9127-244af100ebe1.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Built HTML for search and select inputs as tabs.
   - [x] Add html for arrow up and down HP button .
- [x] Style new additions in CSS.
- [x] Make a view swap for the multi sorter.
- [x] Build a function to query the api for types and super types.
   - [x] Have the function add these as option for the select dropdown menu in the DOM.
   - [x] Have the DOM content loaded trigger this function.
- [x] Listen to the select dropdown response.
   - [x] Clear the collection.
   - [x] Pass only cards from the data collection that match the type or supertype selected into the render.  
- [x] Listen to the HP Button.
   - [x] Create a variable to determine what is currently in view. Null is default, and then true is highest first and false lowest first.
   - [x] In the add a card function, add a new statement to set a new property of data for highestHp, and check every card's HP against the current highestHp and change if higher. Do the same for lowest HP.
   - [x] Using the highest HP, when the HP button is triggered switch current view from Null to true.
   - [x] Loop through the card collection each time for the highestHp decremented by 10 until the lowest HP and if the cards HP matches render it.
   - [x] When HP button is clicked and view is true, loop through the cards starting at the lowest HP and adding the card if it matches, incrementing the HP by 10 till reaching the highestHP.
- [x] Listen to the search input.
   - [x]  Compare the input against each card in the data collection.
   - [x] Make sure the input and compared names are in the same format, lowercase and removed apostrophe's.
   - [x] Render all cards that match the current input.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
