### ISSUE TITLE
Feature: User can build decks.

### ISSUE THREAD

**Issue by krog-kristian** [krog-kristian/tcg-tracker#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can manage up to four decks of cards.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User will be able to add cards from their collection to one of four decks. They will be able to name the deck and remove cards from the deck.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![issue-4-mobile-1](https://user-images.githubusercontent.com/118767169/222524739-df5aa085-4f47-45b2-ace2-01f60d357d3f.png)
![issue-4-mobile-2](https://user-images.githubusercontent.com/118767169/222524757-bca3a8bf-89f9-4199-9b7c-800720f49343.png)
![issue-4-desktop-1](https://user-images.githubusercontent.com/118767169/222524783-f9e0a0c3-df39-4fc6-9d6d-3692b6298aaa.png)
![issue-4-desktop-2](https://user-images.githubusercontent.com/118767169/222524807-c2683c69-6a49-4903-bf01-9f3cea1ef9a2.png)
![issue-4-desktop-3](https://user-images.githubusercontent.com/118767169/222524817-b0c21683-3029-4868-a62b-b99051ae80cb.png)
![issue-2-desktop](https://user-images.githubusercontent.com/118767169/222524867-ce02bff3-d606-4041-980f-f0d95669ff54.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Build HTML for Deck page for mobile.
- [x] Build HTML for Deck page for desktop.
- [x] Add links for deck page in HTML
- [x] Style mobile Deck page.
- [x] Style desktop Deck page.
- [x] Add deck select HTML to collection page.
   - [x] Style collection page deck select.
- [x] Update collection page render to create an add to deck button.
- [x] Update data object to have a decks property with 4 decks objects, that have the property of name, collection and size.
- [x] Listen for clicks on the add to deck buttons on the collection page.
   - [x] Check selected radio button to determine current deck. 
   - [x] Find the current selected card from the data collection and push into the deck.
   - [x] If the deck selected length is 60, do not add it to the deck. 
   - [x] Scroll to top and add flash deck full for 5 seconds in red.
- [x] Have view swap trigger a render of the default deck on the decks page. 
- [x]  On the deck page listen to the deck select buttons. 
   - [x] Have a variable to keep track of selected deck.  
   - [x] Pass the selected deck into the render function. 
   - [x] Add a remove button to the rendered cards.
   - [x] Attach them to the row and attach the row to the container.
   - [x] Have deck select buttons swap selected buttons for other view.
- [x] Listen to the edit pencil button.
   - [x] Pop up a window showing the deck name in an input field. 
   - [x] When they hit the confirm/submit button change the name of the deck to the new name.
   - [x] Change all deck name locations.
   - [x] Add name change function to load.
   - [x] When cancel reset the form and hide the pop up.
- [x] Listen to the clear deck button.
   - [x] When pushed pop up a confirmation window.
   - [x] Cancel will close the window.
   - [x] Build a function to update the deck numbers.
   - [x] Link function to add to deck button.
   - [x] Confirm will reset the decks collection to an empty array.
   - [x] Then will remove the rendered cards.
- [x] In the deck page event listener add a new condition for the remove button.
   - [x] Get the card wrappers ID.
   - [x] Remove the card wrapper from the DOM.
   - [x] Pass cardID into a new function to remove a card.
   - [x] Build function to remove a single card. That finds the first index matching the ID.
   - [x] Then splices that card from the collection.
   - [x] Reduces the size of the deck and does a deck size check call. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
