### ISSUE TITLE
Feature: User can see cards missing from a series.

### ISSUE THREAD

**Issue by krog-kristian** [krog-kristian/tcg-tracker#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see cards missing from a series.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to search through series and sets to see sets of cards. They will then be able to see what cards are missing.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue-5-mobile-1](https://user-images.githubusercontent.com/118767169/222811343-fca0007d-a9fa-4168-a9c3-4b040a7eaefb.png)
![issue-5-mobile-2](https://user-images.githubusercontent.com/118767169/222811352-61b47574-28bf-4d9a-abff-f03b9365d540.png)
![issue-5-desktop-1](https://user-images.githubusercontent.com/118767169/222811374-f5da75a9-49d4-490f-b43f-751edada4381.png)
![issue-5-desktop-2](https://user-images.githubusercontent.com/118767169/222811381-986d7f9f-c065-416b-8b95-d99e248ad684.png)
![issue-5-desktop-3](https://user-images.githubusercontent.com/118767169/222811388-e08b920b-dc12-47ab-b45e-0c99842de090.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a new page for view in HTML with a dropdown select menu, call this page series page.
- [x] Link the new page in the nav bar and hamburger menu.
- [x] Style the new page.
- [x] Query the DOM for sets.
   - [x] Loop through the sets and get all the series names.
   - [x] Use the series names to create the select menu for the dropdown.
   - [x] When a series is chose, render the image as the title for the page.
   - [x] Render the sets images as buttons with their name underneath on the page.
- [x] Create a new page similar to search results called set page.
   - [x] Use the sets logo as the title
   - [x] Underneath have a element to hold the count of the series and cards that match.
   - [x] Then render the cards for the set.
   - [x] Determine how many pages of 50 are in the set.
   - [x] Pass the set render with total pages and current page starting at 1.
   - [x] Request page with set ID for 50cards, is the current page is less than the total pages, increment the page recall the function.
   - [x] When page is equal to the total pages call the card count function to count owned cards of the set and display.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
